---
admins: stuart,tyler,philip
database:
  DATABASE: xy
  DBTYPE: MySQL
  PASSWORD: 1234
  TESTDATABASE: testdatabase
  TESTPASSWORD: testpassword
  TESTUSER: testuser
  USER: xy
installdir: '/xy'
modules: Xy::Base
tables:
  dataseries: dataseries
  poll: poll
  slider: slider
  users: users
test:
  TESTDATABASE: testdatabase
  TESTPASSWORD: testpassword
  TESTUSER: testuser
